version: '3.8'

services:
  docker_course:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: test:v1.0.0
    container_name: docker_course
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    restart: no